export interface AlgorithmMeta {
  type: "sort" | "graph" | "other";
  displayName: string;
  code: string[];
}

export const algorithmRegistry: Record<string, AlgorithmMeta> = {
  bubble_sort: {
    type: "sort",
    displayName: "Пузырьковая сортировка",
    code: [
      "func bubbleSort(arr []int) {",
      "  for i := 0; i < n-1; i++ {",
      "    for j := 0; j < n-i-1; j++ {",
      "      if arr[j] > arr[j+1] {",
      "        arr[j], arr[j+1] = arr[j+1], arr[j]",
      "      }",
      "    }",
      "  }",
      "}",
    ],
  },
  quick_sort: {
    type: "sort",
    displayName: "Быстрая сортировка",
    code: [
      "func quickSort(arr []int, low, high int) {",
      "  if low < high {",
      "    pi := partition(arr, low, high)",
      "    quickSort(arr, low, pi-1)",
      "    quickSort(arr, pi+1, high)",
      "  }",
      "}",
      "func partition(arr []int, low, high int) int {",
      "  pivot := arr[high]",
      "  i := low - 1",
      "  for j := low; j < high; j++ {",
      "    if arr[j] < pivot {",
      "      i++",
      "      arr[i], arr[j] = arr[j], arr[i]",
      "    }",
      "  }",
      "  arr[i+1], arr[high] = arr[high], arr[i+1]",
      "  return i+1",
      "}",
    ],
  },
  merge_sort: {
    type: "sort",
    displayName: "Сортировка слиянием",
    code: [
      "func mergeSort(arr []int, left, right int) {",
      "  if left < right {",
      "    mid := left + (right-left)/2",
      "    mergeSort(arr, left, mid)",
      "    mergeSort(arr, mid+1, right)",
      "    merge(arr, left, mid, right)",
      "  }",
      "}",
      "func merge(arr []int, left, mid, right int) {",
      "  n1 := mid - left + 1",
      "  n2 := right - mid",
      "  L, R := make([]int, n1), make([]int, n2)",
      "  for i := 0; i < n1; i++ { L[i] = arr[left+i] }",
      "  for j := 0; j < n2; j++ { R[j] = arr[mid+1+j] }",
      "  i, j, k := 0, 0, left",
      "  for i < n1 && j < n2 {",
      "    if L[i] <= R[j] {",
      "      arr[k] = L[i]",
      "      i++",
      "    } else {",
      "      arr[k] = R[j]",
      "      j++",
      "    }",
      "    k++",
      "  }",
      "  for i < n1 { arr[k] = L[i]; i++; k++ }",
      "  for j < n2 { arr[k] = R[j]; j++; k++ }",
      "}",
    ],
  },
  bfs: {
    type: "graph",
    displayName: "BFS",
    code: [
      "func BFS(graph Graph, start int) {",
      "  visited := make(map[int]bool)",
      "  queue := []int{start}",
      "  for len(queue) > 0 {",
      "    node := queue[0]",
      "    queue = queue[1:]",
      "    if !visited[node] {",
      "      visited[node] = true",
      "      for _, neighbor := range graph[node] {",
      "        if !visited[neighbor] {",
      "          queue = append(queue, neighbor)",
      "        }",
      "      }",
      "    }",
      "  }",
      "}",
    ],
  },
  dfs: {
    type: "graph",
    displayName: "DFS",
    code: [
      "func DFS(graph Graph, node int, visited map[int]bool) {",
      "  visited[node] = true",
      "  for _, neighbor := range graph[node] {",
      "    if !visited[neighbor] {",
      "      DFS(graph, neighbor, visited)",
      "    }",
      "  }",
      "}",
    ],
  },
  dijkstra: {
    type: "graph",
    displayName: "Дейкстра",
    code: [],
  },
};